import { Component } from '@angular/core';

@Component({
  selector: 'app-collection',
  templateUrl: './collection.component.html',
  styleUrls: ['./collection.component.scss']
})
export class CollectionComponent {
  pictures = [
    { name: "Dogs on a Leash", date: "1775", imgResp1: "imagen1/200.jpg", imgResp2: "imagen1/767.jpg", imgResp3: "imagen1/1135.jpg", imgResp4: "imagen1/1400.jpg", desc: "A tapestry cartoon with two chained dogs, two shotguns, a powder horn, and other hunting implements on a small hill, with a landscape in the background. The resulting tapestry was intended to hang over one of the doors of the dining room of the Prince and Princess of Asturias (the future Carlos IV and his wife, Maria Luis de Parma) at the Monastery of El Escorial."},
    { name: "Hunting Party", date: "1775", imgResp1: "imagen2/200.jpg", imgResp2: "imagen2/769.jpg", imgResp3: "imagen2/1140.jpg", imgResp4: "imagen2/1400.jpg", desc: "Goya uses a single work to present two types of hunting —on foot and on horseback— and various types of individuals. In the foreground, one hunter shoots quail while another follows his dog, which smells prey hiding among the bushes. In the background, two riders hunt a hare being coursed by greyhounds. The study of animals and movement is this work´s greatest contribution."},
    { name: "Dance on the Banks of the Manzanares", date: "1776-1777", imgResp1: "imagen3/200.jpg", imgResp2: "imagen3/773.jpg", imgResp3: "imagen3/1182.jpg", imgResp4: "imagen3/1400.jpg", desc: "This tapestry cartoon represents a popular scene of Majos and Majas dancing Seguidillas on the banks of Madrid´s Manzanares River. In the background, Goya painted the area around the Pontones Bridge, near la Quinta del Sordo, the land and house he bought in 1819. The resultant tapestry was intended to hang in the dining room of the Prince and Princess of Asturias (the future Carlos IV and his wife Maria Luisa de Parma) at the Monastery of El Escorial."},
    { name: "The Colossus", date: "After 1808", imgResp1: "imagen4/200.jpg", imgResp2: "imagen4/941.jpg", imgResp3: "imagen4/1338.jpg", imgResp4: "imagen4/1400.jpg", desc: "A fearsome giant looms over a valley filled with a terrified, scattering multitude in what has on occasions been seen as a reference to the Spanish War of Independence. Although catalogued until recently as an original by Goya and often considered one of his most unique works, the painting has been the subject of intense critical debate in recent years."},
    { name: "The 2nd of May 1808 in Madrid or “The Fight against the Mamelukes”", date: "1814", imgResp1: "imagen5/200.jpg", imgResp2: "imagen5/773.jpg", imgResp3: "imagen5/1197.jpg", imgResp4: "imagen5/1400.jpg", desc: "In 1814, Goya addressed the reagent, Cardinal Luis de Bourbon, offering to make works commemorating events from the War of Independence (1808-1812): 'to perpetuate, with a paintbrush, the most notable and heroic actions or scenes of our glorious uprising against the tyrant of Europe'. The present work depicts the popular riot of 2 May, 1808, when the people of Madrid attacked the Mamelukes —Turkish soliders in Napolean´s French Army— who were taking the younger children of Carlos IV and Maria Luisa to France."},
    { name: "Asmodea", date: "1820-1823", imgResp1: "imagen6/200.jpg", imgResp2: "imagen6/855.jpg", imgResp3: "imagen6/1265.jpg", imgResp4: "imagen6/1400.jpg", desc: "The mural paintings that decorated the house known as “la Quinta del Sordo,” where Goya lived have come to be known as the Black Paintings, because he used so many dark pigments and blacks in them, and also because of their somber subject matter. The private and intimate character of that house allowed the artist to express himself with great liberty. He painted directly on the walls in what must have been mixed technique, as chemical analysis reveals the use of oils in these works."}
  ]
}
